[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[dev]
  port = 8888
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["netlify/bin/**"]
  node_bundler = "esbuild"

[functions."cron-trigger"]
  schedule = "*/5 * * * *"

